server:
  port: 8001
  servlet:
    context-path: /spring-graphql-mutation-vs-rest-post-put-patch-delete-methods

spring:

  graphql:
    path: /customers-graphql
    schema:
      locations: classpath:graphql/
    graphiql:
      enabled: true # Docs can be accessed http://localhost:8001/spring-graphql-mutation-vs-rest-post-put-patch-delete-methods/graphiql

  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Used for test, it logs queries
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
              MongoTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
